name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          # Required to pull down the theme, 'kayal' which is installed as a submodule.
          submodules: recursive

      - name: Set up deploy keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'  # TODO: pin version

      # My wife is judging me harshly for deploying to a server instead of using S3 or GitHub Pages.
      # She literally made a joke about using, "...good 'ol Nginx" not knowing that I was literally doing that.
      # I stand by my choices .... (ish)
      - name: Build and deploy Hugo sites
        run: |
          ls -d *.lol | while read "dname"
          do
            echo -e "\n\n==== NOW BUILDING ${dname} ===="
            hugo --source ${dname} --destination public
            if [ -f "${dname}/deploy" ]; then
              ls -lah ${dname}
              ls -lah ${dname}/public/
              # rsync -av -e "ssh -o StrictHostKeyChecking=no" ${dname}/public/ ${{ secrets.DEPLOY_USER }}@${dname}:/var/www/${dname}/
            fi
          done
